<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manish" failures="2" tests="9" name="Test" time="0.135" errors="0" timestamp="2023-11-04T00:48:45 IST">
  <testcase classname="FailedTestcase.Testcase1" name="test1" time="0.016">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="FailedTestcase.Testcase1" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="FailedTestcase.Testcase1" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="FailedTestcase.Testcase1" name="test1" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at FailedTestcase.Testcase1.test1(Testcase1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="FailedTestcase.Testcase1" name="test2" time="0.001"/>
  <testcase classname="FailedTestcase.Testcase1" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="FailedTestcase.Testcase1" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="FailedTestcase.Testcase1" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="FailedTestcase.Testcase1" name="test3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at FailedTestcase.Testcase1.test3(Testcase1.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
